version: '3.9'
services:
  postgres:
    image: 'postgres'
    volumes:
      - pgdata:/pgdata
    environment:
      PGDATA: pgdata
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB

  backend:
    build: .
    volumes: 
      - /app/node_modules
      - /app/dist
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  pgdata:
